x-common-build-args: &build-args
  PYTHON_VERSION: "3.10"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
      args:
        <<: *build-args
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
