ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim

# Set working directory
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install Jupyter Notebook & JupyterLab
RUN pip install notebook jupyterlab

# Copy the entrypoint script
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Copy the rest of the code
COPY . .

# Expose port for Jupyter Notebook
EXPOSE 8888

# Set entrypoint
ENTRYPOINT ["/entrypoint.sh"]

# Run Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
